### ISSUE TITLE
Please add context to deprecation warning 

### ISSUE THREAD

**Issue by jasnow** [ruby/rake#119]
Missing context (filename, line number, etc) with this warning:
**[DEPRECATION] last_comment is deprecated. Please use last_description instead.**

Found in this commit: https://github.com/ruby/rake/commit/3948349a82a2522f1d8293093164ef395bee542d

**Comment by jasnow** [comment]
Found the line that helped me in lib/rake/task_manager.rb (added it twice):
```
caller_locations(1, 1).first.tap{|loc| puts "#{loc.path}:#{loc.lineno}:"}
```

**Comment by hsbt** [comment]
I have no motivation for improvement of deprecated function. Welcome pull request with testcase.

**Comment by jasnow** [comment]
Okay but without context it took a LONG time (several hours) to find out where the problem was so I could fix it or tell the correct gem to fix it.

**Comment by krisleech** [comment]
@jasnow I bet Rake saved you many more hours than the several it cost you recently. And how much did you pay for Rake...

**Comment by jasnow** [comment]
HUGE - improving the warning message for the next person to get it

**Comment by gc-olivierho** [comment]
Thank you for the line of code to add in order to understand from which gem(s) the warnings were coming.
It turned out to be from the yard gem for me. Unfortunately, the latest release is 0.8.7.6 in October 2015, and does not yet contain the fix for the deprecation warning.
However, that code (yard gem) belongs to hsbt (who closed this issue), and the fix is already present in the master branch, so maybe we will soon have a release removing the warning.

Just for readers curiosity, we use yard in the frame of our Redmine website installation, and the deprecation warning is shown whatever rake command we run for Redmine.

**Comment by jasnow** [comment]
@gc-olivierho - You are welcome
