### ISSUE TITLE
specifying bash (instead of sh) to run shell commands

### ISSUE THREAD

**Issue by kianho** [ruby/rake#26]
### Update
A makeshift solution is described here - http://stackoverflow.com/questions/17044325/use-bin-bash-for-x-in-ruby

If `/bin/sh` is hardcoded into ruby, it would make this more of an issue for ruby rather than a rake (feel free close/delete this issue).

### Original Issue
Is there a way to configure rake to use `bash` (`/bin/bash`) rather than `sh` (`/bin/sh`) as the default shell interpreter?

I'd like to take advantage of BASH-centric features in rake, such as  [process substitution](http://tldp.org/LDP/abs/html/process-sub.html), which are not implemented in `sh`:

For example,
```ruby
task :default do
  `cat <( seq 1 10 )`
end
```
produces the error:
```bash
sh: 1: Syntax error: "(" unexpected
```
since `sh` appears to be the default Rake shell.

Something analogous to setting [`SHELL:=/bin/bash` in Makefiles](https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html) would be useful if it doesn't already exist.

My googling has come up empty regarding this feature in Rake.

### Further reading
- http://stackoverflow.com/questions/589276/how-can-i-use-bash-syntax-in-makefile-targets

**Comment by EricIO** [comment]
According to http://ruby-doc.org/core-2.2.1/Kernel.html#method-i-exec
`The standard shell always means "/bin/sh" on Unix-like systems`

But on most unix systems `/bin/sh` is just symlinked to some other shell (I have both `/bin/sh -> /bin/bash` and `/bin/sh -> /bin/dash` on my systems) and I don't get a syntax error with the code provided with bash version 4.3.33. Looks like this is hardcoded into ruby (https://github.com/ruby/ruby/blob/ca6b174078fa15f33655be704d9409fdbc4f9929/process.c#L1120).

**Comment by kianho** [comment]
thanks for the insight @EricIO

**Comment by binaryphile** [comment]
I came up with another workaround which invokes bash from /bin/sh.

It's a bit involved but it allows you to still use the rake #sh method.

Although it's not necessary for the workaround, I'm using heredocs to keep things readable.  Unfortunately that adds a wrinkle that I've dealt with here, but it's slightly more complicated.

The syntax goes:

```
task :hello_world do
  sh <<-EOS.strip_heredoc
    cat <<BASH | /bin/bash
    echo "Hello, world!"
    BASH
  EOS
end

class String
  def strip_heredoc
    gsub(/^#{scan(/^[ \t]*(?=\S)/).min}/, ''.freeze)
  end
end
```

#strip_heredoc is borrowed from rails: 

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/string/strip.rb

You could probably get it by requiring active_support, or maybe it's autoloaded when you're in a rails project, but I was using this outside rails and so had to def it myself.

The way this works is by feeding the inside heredoc to bash's stdin.  Note that it is running within the context of /bin/sh, so it's a POSIX heredoc not a ruby one.  That dictates that the end marker is in the first column of the heredoc (note that POSIX's <<- operator only works on tabs and I don't want to use tabs).

Because the bash lines are within a ruby heredoc, they would normally need to begin on the left column in order to satisfy the POSIX heredoc requirements.  However, the strip_heredoc function will deindent it for you.  That allows you to use the nice indenting (although the BASH end marker does need to line up with the commands inside).

So far this is working fine for me.

**Comment by xiangshuai** [comment]
Few days ago I was meeting the same problem and I fix it as following:
create bash method:
```
def bash cmd 
    cmd = "set -o pipefail && #{cmd}"
    system("bash -c #{cmd.shellescape}")
    cmd_status = $?
    if cmd_status != 0
        raise "'#{cmd}' execution failed (exit code: #{cmd_status})"
    end 
end 
```
so now you can call bash func:
`bash 'echo false | echo true'`
